import { AdminSideBar } from "@/components/AdminSideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className="flex">
      <AdminSideBar></AdminSideBar>
      <div className="w-full min-h-screen bg-gray-100 p-8">{children}</div>
    </body>
  );
}
